CREATE TABLE accounts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(20)    NOT NULL UNIQUE,
    owner_name     VARCHAR(255)   NOT NULL,
    balance        NUMERIC(19,2)  NOT NULL,
    account_type   VARCHAR(20)    NOT NULL CHECK (account_type IN ('SAVINGS', 'CHECKING')),
    status         VARCHAR(20)    NOT NULL CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED')),
    version        BIGINT         NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ    NOT NULL,
    updated_at     TIMESTAMPTZ    NOT NULL
);

CREATE TABLE users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(20)  NOT NULL CHECK (role IN ('USER', 'ADMIN'))
);
